export const COMMODITY_CODES = {
  BRIDGE_BEAMS: 'BRGBEAM',
  EMPTY: 'EMPTYXX',
  LAMINATED_BEAMS: 'LAMBEAM',
  NON_REDUCIBLE_LOADS: 'NONREDU',
  NONE: 'XXXXXXX',
  REDUCIBLE_LOADS: 'REDUCBL',
} as const;
