export const PERMIT_CODES = {
  // TERM
  TERM_OVERSIZE: 'TROS',
  TERM_OVERWEIGHT: 'TROW',
  HIGHWAY_CROSSING: 'HC',
  // SINGLE TRIP
  EXTRA_PROVINCIAL_TEMP_OPERATING_PERMIT: 'EPTOP',
  SINGLE_TRIP_OVERWEIGHT: 'STOW',
  SINGLE_TRIP_OVERSIZE: 'STOS',
  SINGLE_TRIP_OVERSIZE_OVERWEIGHT: 'STWS',
  EMPTY_SINGLE_TRIP_OVER_LENGTH_27_5: 'STWSE',
  SINGLE_TRIP_GVW_INCREASE: 'STGVWI',
  RIG_MOVE: 'RIG',
  INCREASED_GVW: 'IGVW',
  // NON RESIDENT
  QUARTERLY_ICBC_BASIC_INSURANCE_FR: 'QRFR',
  QUARTERLY_NON_RESIDENT: 'NRQCV',
  SINGLE_TRIP_ICBC_BASIC_INSURANCE_FR: 'STFR',
  SINGLE_TRIP_NON_RESIDENT: 'NRSCV',
  // MOTIVE FUEL USER PERMIT
  MOTIVE_FUEL_USER_PERMIT: 'MFP',
} as const;