import { TRAILER_CODES, TrailerCode } from './trailer-codes';

export const SEMI_TRAILER_CODES = new Set<TrailerCode>([
  TRAILER_CODES.EXPANDO_SEMI_TRAILERS,
  TRAILER_CODES.FIXED_EQUIPMENT_CONVEYORS,
  TRAILER_CODES.FIXED_EQUIPMENT_COUNTER_FLOW_ASPHALT_DRUM_MIXERS,
  TRAILER_CODES.FIXED_EQUIPMENT_PORTABLE_ASPHALT_BAGHOUSES,
  TRAILER_CODES.FIXED_EQUIPMENT_SEMI_TRAILERS,
  TRAILER_CODES.FIXED_EQUIPMENT_WHEELER_SEMI_TRAILERS,
  TRAILER_CODES.HIBOYS_EXPANDOS,
  TRAILER_CODES.HIBOYS_FLAT_DECKS,
  TRAILER_CODES.OIL_AND_GAS_OVERSIZE_OILFIELD_FLAT_DECK,
  TRAILER_CODES.PLATFORM_TRAILERS,
  TRAILER_CODES.PLATFORM_TRAILERS_WHEELERS,
  TRAILER_CODES.POLE_TRAILERS,
  TRAILER_CODES.READY_MIX_CONCRETE_PUMP_SEMI_TRAILERS,
  TRAILER_CODES.SEMI_TRAILERS,
  TRAILER_CODES.SEMI_TRAILERS_SINGLE_DOUBLE_DROP_STEP_DECK_LOWBED,
  TRAILER_CODES.SEMI_TRAILERS_WITH_CRANE,
  TRAILER_CODES.SEMI_TRAILERS_SPREAD_TANDEMS,
  TRAILER_CODES.SEMI_TRAILERS_WHEELERS,
  TRAILER_CODES.SEMI_TRAILERS_WIDE_WHEELERS,
]);

export function isSemiTrailerType(vehicleType: string): boolean {
  return SEMI_TRAILER_CODES.has(vehicleType as TrailerCode);
}
