---
name: CI/CD Pipleine For Simple Package Publishing
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed for provenance data generation

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      
      - name: Injecting Semver Into Package.json
        run:  |
          cat package.json | jq '. + { "version": "${{ steps.semver.outputs.next }}" }' | tee package.json

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci 
      - run: tsc
      - run: npm test
      
      - name: Publish Package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        run: |
          gh release create "${{ steps.semver.outputs.next }}" \
          --repo="${{ github.repository }}" \
          --title="${{ steps.semver.outputs.next }}" \
          --generate-notes
