---
name: CI/CD Pipleine For Simple Package Publishing
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write # needed for provenance data generation
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noNewCommitBehavior: warn

      - name: Skip Deploy if No Version Bump
        if: ${{ steps.semver.outputs.next == '' }}
        run: echo "No version bump detected. Skipping deploy."

      - name: Injecting Semver Into Package.json
        if: ${{ steps.semver.outputs.next != '' }}
        run:  |
          cat package.json | jq '. + { "version": "${{ steps.semver.outputs.next }}" }' | tee package.json

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm install genversion --save-dev
      - run: npx genversion -e src/version.ts
      - run: tsc
      - run: npm test
      
      - name: Publish Package
        if: ${{ steps.semver.outputs.next != '' }}
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release 
        if: ${{ steps.semver.outputs.next != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.semver.outputs.next }}" \
          --repo="${{ github.repository }}" \
          --title="${{ steps.semver.outputs.next }}" \
          --generate-notes
