---
name: CI/CD Pipleine For Simple Package Publishing
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      
      - name: Injecting Semver Into Package.json
        run:  |
          echo "version: ${{ steps.semver.outputs.next }}"
          cat package.json | jq . + { "version": "${{ steps.semver.outputs.next }}" }
          cat package.json | jq . + { "version": "${{ steps.semver.outputs.next }}" } > package.json
          cat package.json

      - name: Build Package
        run:  | 
          npm ci; 
          tsc;  
          npm test
      
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
          token: ${{ github.token }}

      - name: Publish Package
        run:  npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
